```{r warning=FALSE, echo=FALSE, message=FALSE}
library(ggplot2)
library(reshape2)
theme_set(theme_bw())
```

Nosofsky Similarity
===================

Nosofsky similarity is governed by a single parameter alpha.

```{r}
get.confusion.matrix = function(states,alpha){
  ns = length(states)
  if (alpha <= 0){
    return(diag(rep(1,ns)))
  }
  C = matrix(0,nrow=ns, ncol=ns)
  for (i in 1:ns){
    for (j in 1:ns){
      C[i,j] = exp( - (states[i]-states[j])^2 / (alpha^2) )
    }
  }
  return(C)
}
```

We can plot the similarity for different distances for different values of alpha.

```{r}
ns = 50
alphas = c(0.05, 0.1, 0.2, 0.3)

states = seq(0,1,length.out=ns)

out = matrix(0,nrow=length(alphas),ncol=ns)
outNorm = matrix(0,nrow=length(alphas),ncol=ns)

for (a in 1:length(alphas)){
  out[a,] = get.confusion.matrix(states,alphas[a])[1,]
  outNorm[a,] = prop.table(get.confusion.matrix(states,alphas[a]),1)[1,]
}

simDF = data.frame(distance = rep(states,2*length(alphas)),
                   alpha_i = factor(rep(rep(alphas, each=ns),2)),
                   normalized = factor(rep(c("Nosofsky similarity", "confusion probability"),each=ns*length(alphas)),
                                       levels = c("Nosofsky similarity", "confusion probability")),
                   similarity = c(as.vector(t(out)),as.vector(t(outNorm)))  )

p = ggplot(simDF, aes(x = distance, y = similarity, shape = alpha_i))+
  geom_line(color='grey')  + geom_point()  + 
  facet_grid(normalized~. , scales = "free") + ylab("") + 
  xlab("distance in physical space") +
  scale_shape_discrete(name="imprecision")

show(p)

ggsave(p, file="paper/plots/NosofskySim.pdf", width=7, height=4)

```


